$ErrorActionPreference = 'Stop'
# Run after downloading https://pki.goog/roots.pem to this sketch directory.
$pem = Get-Content (Join-Path $PSScriptRoot 'google-roots.pem') -Raw
$allCertificates = [regex]::Matches($pem, '-----BEGIN CERTIFICATE-----[\s\S]*?-----END CERTIFICATE-----')
if ($allCertificates.Count -lt 4) { throw 'Incomplete CA bundle; refusing to replace header.' }
$certificates = @()
foreach ($item in $allCertificates) {
    $base64 = $item.Value -replace '-----BEGIN CERTIFICATE-----|-----END CERTIFICATE-----|\s', ''
    $certificate = [System.Security.Cryptography.X509Certificates.X509Certificate2]::new([Convert]::FromBase64String($base64))
    if ($certificate.Subject -match 'CN=GTS Root R(1|4),') { $certificates += $item }
    $certificate.Dispose()
}
if ($certificates.Count -ne 2) { throw "Expected GTS Root R1 and R4; found $($certificates.Count)." }
$body = ($certificates | ForEach-Object { $_.Value }) -join "`n"
$header = "#pragma once`n// Minimal Firebase bundle: GTS Root R1 (RTDB) and GTS Root R4 (Identity Toolkit).`n// Source: https://pki.goog/roots.pem; refresh and verify active chains every six months.`n// Generated by Update-CaBundle.ps1. Recompile and upload after refreshing.`nstatic const char GOOGLE_ROOT_CA_BUNDLE[] PROGMEM = R`"PEM(`n$body`n)PEM`";`n"
[IO.File]::WriteAllText((Join-Path $PSScriptRoot 'firebase_ca.h'), $header)
Write-Output "Validated and generated minimal CA bundle: GTS Root R1 and R4."
